### ISSUE TITLE
考虑支持DRACOLoader.js吗

### ISSUE THREAD

**Issue by Primary-Traxex** [yannliao/threejs-example#13]
项目中很经常会遇到压缩的gltf文件, 如果能支持解压插件DRACOLoader.js, 那是很舒服了

**Comment by HolyShitKillingMachine** [comment]
我也遇到这个问题，如果可以支持解压缩的话，那么，小程序上跑3D会更舒畅

**Comment by yannliao** [comment]
我写了demo代码，上传到dev   你们可以看下能不能完善下～

**Comment by Primary-Traxex** [comment]
可以大致说说你的思路吗

**Comment by HolyShitKillingMachine** [comment]
> 我写了demo代码，上传到dev 你们可以看下能不能完善下～

地址在哪儿。。。。我没看到，能否给个地址

**Comment by yannliao** [comment]
> > 我写了demo代码，上传到dev 你们可以看下能不能完善下～
> 
> 地址在哪儿。。。。我没看到，能否给个地址

在dev 分支里面
